# .nosana-ci.yml
nosana:
  description: Soteria Code Scan

global:
  image: projectserum/build:v0.27.0
  env:
    CARGO_TERM_COLOR: always

  trigger:
    branch:
      - main
           
#    pull_request:
#      branches:
#        - main

jobs:
  - name: build and audit
    commands:
      - echo First Build Step
      - pwd
      - env
      - rustup default stable
      - cargo build --locked
      
      - echo Installing BPG toolchain
      - pwd
      - |
          rustup default stable
          cd /root/.local/share/solana/install/active_release/bin/sdk/bpf
          rm -rf dependencies/*
          ./scripts/install.sh
          rustup default bpf
          cd /root/project/
          cargo update
          
      - echo install Soteria Auditor
      - sh -c "$(curl -k https://supercompiler.xyz/install)"
      - export PATH=$PWD/soteria-linux-develop/bin/:$PATH
      
      - echo Auditing programs/network
      - export PATH=$PWD/soteria-linux-develop/bin:$PATH
      - cd programs/network
      - soteria -analyzeAll .
      - cd ../..
      
      - echo Auditing programs/thread
      - export PATH=$PWD/soteria-linux-develop/bin:$PATH
      - cd programs/thread
      - soteria -analyzeAll .
      - cd ../..
      
      - echo Auditing webhook
      - export PATH=$PWD/soteria-linux-develop/bin:$PATH
      - cd programs/webhook
      - soteria -analyzeAll .
