# .nosana-ci.yml
nosana:
  description: Clockwork CodeScan, Bump and Release

global:
  image: projectserum/build:v0.27.0
  environment:
    CARGO_TERM_COLOR: always
    WORKDIR: /workdir/nosana-ci/
    ANCHOR_VERSION: v0.27.0
    PUBLISH_PREFIX: clockwork
    RUST_BACKTRACE: full
    GIT_USER_NAME: "Clockwork XYZ"
    GIT_USER_EMAIL: team@clockwork.xyz
    # CARGO_REGISTRY_TOKEN:
    #   type: nosana/secret
    #   endpoint: https://secrets.nosana.ci
    #   value: CRATES_IO_TOKEN

  trigger:
    branch:
      - main

jobs:

  - name: Release
    commands:
      - echo Release Step
      - rustup default stable
      - cd $WORKDIR

      - echo Build release
      - cargo build --release --locked
      - ls -lah target/release

      - echo Grant permission to scripts
      - chmod +x ./scripts/ci/create-tarball.sh
			- chmod +x ./scripts/build-all.sh

      - echo Build release tarball
      - ./scripts/build-all.sh clockwork_release
      - ls -lah clockwork_release

      # TODO uncomment when CARGO_REGISTRY_TOKEN is set in `global.enviroment`
      # - cargo install publish-workspace
      # - cargo +stable publish-workspace --allow-dirty --no-verify