[package]
name = "nosana_clockwork-sdk"
version = "2.0.15"
description = "An SDK for building automated programs on Solana"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://clockwork.xyz"
repository = "https://github.com/clockwork-xyz/clockwork"
documentation = "https://docs.clockwork.xyz"
readme = "./README.md"
keywords = ["solana"]

[lib]
name = "nosana_clockwork_sdk"

[dependencies]
anchor-lang = "0.27.0"
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
nosana_clockwork-thread-program = { path = "../programs/thread", features = ["cpi"], version = "2.0.15" }
nom = "~7"
once_cell = "1.5.2"

[features]
default = []
